Repository VAIBHAVBABELE/vaibhavbabele.github.io, pull requests merged in 2025-09, with the labels that each got.

#390 feat: Improve Inconsistent Preview/Download button layout in Subject …
  pages/paper.css
  pages/subject.html
Labels: bug, OSCI25, Easy

#394 Redesigned landing page with new layout
  index.css
  index.html
Labels: enhancement, OSCI25, intermediate

#415 Redesigned the papers page to match the notes page
  pages/paper.css
  pages/paper.html
Labels: enhancement, gssoc25, LEVEL 2

#424 Add Student Marketplace Feature
  index.html
  pages/image/Bed.png
  pages/image/Books.png
  pages/image/Diary.png
  pages/image/Headphones.png
  pages/image/Lab-Coat.png
  pages/image/Laptop.png
  pages/image/Lunch box.png
  pages/image/Marketplace.png
  pages/image/Mouse.png
  pages/image/Mug.png
  pages/image/Notebook.png
  pages/image/Stationery.png
  pages/image/Sticky notes.png
  pages/image/USB drive.png
  pages/image/Yoga Mat.png
  pages/image/bag.png
  pages/image/bottle.png
  pages/image/calculator.png
  pages/image/charger.png
  pages/image/cycle.png
  pages/image/desk lamp.png
  pages/product-list.html
  pages/registration-complete.html
  pages/student-marketplace.css
  pages/student-marketplace.html
  pages/student-marketplace.js
Labels: feature, OSCI25, hard

#435 Enhance PR contributors page
  osci-logo.png
  pages/certificate/certificate.js
  pages/pr-contribution/PR_DESCRIPTION_FINAL.md
  pages/pr-contribution/pr-contributor.css
  pages/pr-contribution/pr-contributors.html
Labels: enhancement, gssoc25, level 2

#455 Fix minor chanhes and seamless dark mode transition
  index.css
  index.html
  index.js
  pages/ai-assistant.html
  pages/cgpa-calculator.html
  pages/contact.css
  pages/feedback.html
  pages/gateway.html
  pages/infrastructure.html
  pages/paper.css
  pages/paper.html
  pages/placement-updates.html
  pages/placement.css
  pages/product-list.html
  pages/scholarship.css
  pages/student-marketplace.css
  pages/student-marketplace.html
  pages/subject.html
  pages/tech.html
Labels: enhancement, gssoc25, level 2
