Repository VAIBHAVBABELE/vaibhavbabele.github.io, pull requests merged in 2025-08, with the labels that each got.

#238 Fixed resource page link and CSS path issue
  games/gamess.html
  games/hangman.html
  games/memory.html
  games/quiz.html
  games/typing.html
  index.html
  index.js
  pages/404.html
  pages/announcement-table.html
  pages/assistant/assistant.css
  pages/assistant/assistant.html
  pages/certificate/certificate.html
  pages/cgpa-calculator.html
  pages/contact.html
  pages/gallery.html
  pages/gateway.html
  pages/infrastructure.html
  pages/paper.html
  pages/pr-contribution/pr-contributors.html
  pages/privacy.css
  pages/privacy.html
  pages/quantum.html
  pages/resorces.html
  pages/subject.html
  pages/summary/summary.css
  pages/summary/summary.html
  pages/summary/summary.js
  pages/terms.html
  pages/test.html
  pages/user-experience-table.html
Labels: enhancement, gssoc25, LEVEL 2

#294 fix: improve dark mode accessibility for calculator tabs and results
  index.css
Labels: bug, gssoc25, level 1

#318 Build Syllabus View Service
  images/syllabus.avif
  index.html
  pages/syllabus/syllabus.css
  pages/syllabus/syllabus.html
  pages/syllabus/syllabus.js
Labels: frontend, OSCI25, Easy

#328 Updated terms final[OSCI'25]
  pages/terms.css
  pages/terms.html
  pages/terms.js
Labels: frontend, OSCI25, Easy

#352 Form validation added
  pages/contact.html
  pages/contact.js
Labels: bug, OSCI25, Easy

#374 enhanced games section
  games/games.css
  games/gamess.html
  games/hangman.html
  games/quiz.html
Labels: enhancement, gssoc25, level 3
