Repository VAIBHAVBABELE/vaibhavbabele.github.io, pull requests merged in 2025-07, with the labels that each got.

#31 Feature/dynamic date
  404.html
  contact.html
  gateway.html
  index.html
  index.js
  paper.html
  privacy.html
  quantum.html
  resorces.html
  subject.html
  terms.html
Labels: good first issue, Gssoc25, frontend, LEVEL 1

#37 Fix: UI issues in announcement and user experience tables (Closes #16, #17)
  announcement-table.htm
  index.css
  index.html
  user-experience-table.html
Labels: enhancement, Gssoc25, LEVEL 2

#64 [Feature]: Add PR Showcase Page with Contributors, GsSOC
  index.html
  pr-contributors.html
Labels: Gssoc25, frontend, feature, LEVEL 3

#40 Updated: Gallery Image Hover Text Alignment (Closes issue #28)
  index.css
Labels: enhancement, Gssoc25, LEVEL 2

#106 Optimized the tables for small screens
  RESUME/index.html
  announcement-table.htm
  index.html
  user-experience-table.html
Labels: enhancement, Gssoc25, frontend, LEVEL 2

#109 Upd footer
  gallery.html
  index.js
  privacy.html
  terms.html
Labels: enhancement, Gssoc25, LEVEL 2

#146 FIX : Poor Visibility of Headings in Services Section (Dark Mode) #133
  index.css
Labels: enhancement, Gssoc25, frontend, LEVEL 1
